name: Build/Push App for Development
on:
  push:
    branches:
      - dev

jobs:
  release:
    name: Release
    steps:
      - name: Build Image(s)
        uses: https://${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/gitea-workflows-builder@main
        with:
          registry_url: ${{ vars.LOCAL_ACR_URL }}
          registry_username: ${{ vars.LOCAL_ACR_USERNAME }}
          registry_password: ${{ secrets.LOCAL_ACR_PASSWORD }}
          development: true

  test:
    name: Test
    needs: 
      - release
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo "${GITHUB_REPOSITORY##*/}") >> $GITHUB_OUTPUT
          echo DATE_RELEASE=$(echo "`date +'%Y.%m.%d'`") >> $GITHUB_OUTPUT

      - name: Run Container & Capture Logs
        run: |
          CONTAINER_NAME="${{ steps.meta.outputs.REPO_NAME }}-auto-test"
          if docker ps -a --filter "name=$CONTAINER_NAME" --format "{{.ID}}" | grep -q .; then
            echo "Stopping and removing existing container: $CONTAINER_NAME..."
            docker stop $CONTAINER_NAME
            docker rm -f $CONTAINER_NAME
          fi
          docker pull ${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.DATE_RELEASE }}-dev
          docker run --name $CONTAINER_NAME \
            -e FIREWALL_HOST=${{ vars.FIREWALL_HOST }} \
            -e FIREWALL_USERNAME=${{ vars.FIREWALL_USERNAME }} \
            -e FIREWALL_PASSWORD=${{ secrets.FIREWALL_PASSWORD }} \
            -e SFTP_HOST=${{ vars.SFTP_HOST }} \
            -e SFTP_USERNAME=${{ vars.SFTP_USERNAME }} \
            -e SFTP_PASSWORD=${{ secrets.SFTP_PASSWORD }} \
            -e SFTP_PATH="/backup/network_configs__TEST" \
            -e PUSHOVER_USER_KEY=${{ secrets.PUSHOVER_USER }} \
            -e PUSHOVER_APP_TOKEN=${{ secrets.PUSHOVER_TOKEN }} \
            ${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.DATE_RELEASE }}-dev \
            bash -c "/app/setup.sh && /app/run.sh"
          docker wait $CONTAINER_NAME
          docker logs $CONTAINER_NAME > logs.txt
          docker rm $CONTAINER_NAME

      - name: Check If Backed Up File Exists in SFTP
        run: |
          BACKUP_CONFIG_FILE=${{ vars.FIREWALL_HOST }}__config__${{ steps.meta.outputs.DATE_RELEASE }}.xml
          sshpass -p '${{ secrets.SFTP_PASSWORD }}' | sftp -o StrictHostKeyChecking=no ${{ vars.SFTP_USERNAME }}:${{ vars.SFTP_HOST }} <<< /backup/network_configs__TEST/$BACKUP_CONFIG_FILE
          if [ $? -eq 0 ]; then
            echo "Backup file found in SFTP endpoint!"
            exit 0
          else
            echo "Backup file not found in SFTP endpoint!"
            exit 1
          fi

      - name: Send Logs via Email
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: ${{ vars.SMTP_SERVER }}
          server_port: ${{ vars.SMTP_PORT }}
          username: ${{ vars.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          secure: true
          to: ${{ vars.SMTP_RECEIVER }}
          from: Gitea DevOps
          subject: Gitea DevOps - Test Results for ${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.DATE_RELEASE }}-dev
          body: file://logs.txt
          ignore_cert: true

  report:
    name: Report
    continue-on-error: true
    needs:
      - release
      - test
    steps:
      - name: Notify User
        uses: https://${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/gitea-workflows-notification@dev
        with:
          success: needs.release.result == 'success' && needs.test.result == 'success'
          development: true
          pushover_user: ${{ secrets.PUSHOVER_USER }}
          pushover_token: ${{ secrets.PUSHOVER_TOKEN }}
