name: Build/Push App for Development
on:
  push:
    branches:
      - dev

jobs:
  release:
    name: Release
    steps:
      - name: Build Image(s)
        uses: https://${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/gitea-workflows-builder@main
        with:
          registry_url: ${{ vars.LOCAL_ACR_URL }}
          registry_username: ${{ vars.LOCAL_ACR_USERNAME }}
          registry_password: ${{ secrets.LOCAL_ACR_PASSWORD }}
          development: true

  test:
    name: Test
    needs: 
      - release
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo "${GITHUB_REPOSITORY##*/}") >> $GITHUB_OUTPUT
          echo DATE_RELEASE=$(echo "`date +'%Y.%m.%d'`") >> $GITHUB_OUTPUT

      - name: Run container and capture logs
        env:
          FIREWALL_HOST: ${{ vars.FIREWALL_HOST }}
          FIREWALL_USERNAME: ${{ vars.FIREWALL_USERNAME }}
          FIREWALL_PASSWORD: ${{ secrets.FIREWALL_PASSWORD }}
          SFTP_HOST: ${{ vars.SFTP_HOST }}
          SFTP_USERNAME: ${{ vars.SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          SFTP_PATH: /backup/network_configs__TEST
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER }}
          PUSHOVER_APP_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        run: |
          CONTAINER_NAME="${{ steps.meta.outputs.REPO_NAME }}-auto-test"
          if docker ps -a --filter "name=$CONTAINER_NAME" --format "{{.ID}}" | grep -q .; then
            echo "Stopping and removing existing container: $CONTAINER_NAME..."
            docker stop $CONTAINER_NAME
            docker rm -f $CONTAINER_NAME
          fi
          docker run --name $CONTAINER_NAME ${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.DATE_RELEASE }}-dev /app/setup.sh
          docker wait $CONTAINER_NAME
          docker logs $CONTAINER_NAME > logs.txt
          docker rm $CONTAINER_NAME

      - name: Send Logs via Email
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: ${{ vars.SMTP_SERVER }}
          server_port: ${{ vars.SMTP_PORT }}
          username: ${{ vars.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          secure: true
          to: ${{ vars.SMTP_RECEIVER }}
          from: Gitea DevOps
          subject: Gitea DevOps - Test Results for ${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.DATE_RELEASE }}-dev
          body: Please see attached logs file.
          attachments: logs.txt
          ignore_cert: true

  report:
    name: Report
    continue-on-error: true
    needs:
      - release
      - test
    steps:
      - name: Notify User
        uses: https://${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/gitea-workflows-notification@main
        with:
          success: needs.release.result == 'success' && needs.test.result == 'success'
          development: true
          pushover_user: ${{ secrets.PUSHOVER_USER }}
          pushover_token: ${{ secrets.PUSHOVER_TOKEN }}
