name: Build/Push App for Development
on:
  push:
    branches:
      - dev

jobs:
  release:
    name: Release
    steps:
      - name: Build Image(s)
        uses: https://${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/gitea-workflows-builder@main
        with:
          registry_url: ${{ vars.LOCAL_ACR_URL }}
          registry_username: ${{ vars.LOCAL_ACR_USERNAME }}
          registry_password: ${{ secrets.LOCAL_ACR_PASSWORD }}
          development: true

  test:
    name: Test
    needs: 
      - release
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/${{ github.repository }}:latest-dev
      env:
        FIREWALL_HOST: ${{ vars.FIREWALL_HOST }}
        FIREWALL_USERNAME: ${{ vars.FIREWALL_USERNAME }}
        FIREWALL_PASSWORD: ${{ secrets.FIREWALL_PASSWORD }}
        SFTP_HOST: ${{ vars.SFTP_HOST }}
        SFTP_USERNAME: ${{ vars.SFTP_USERNAME }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        SFTP_PATH: /backup/network_configs__TEST
        PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER }}
        PUSHOVER_APP_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
    steps:
      - name: Install Dependencies
        run: bash /app/setup.sh

      - name: Perform Test Backup
        run: bash /app/run.sh

  report:
    name: Report
    continue-on-error: true
    needs:
      - release
      - test
    steps:
      - name: Notify User
        uses: https://${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/gitea-workflows-notification@main
        with:
          success: needs.release.result == 'success' && needs.test.result == 'success'
          development: true
          pushover_user: ${{ secrets.PUSHOVER_USER }}
          pushover_token: ${{ secrets.PUSHOVER_TOKEN }}
