name: Build/Push App for Development
on:
  push:
    branches:
      - dev

env:
  IMAGE_BASE: ${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}
  IMAGE_TAG_ENDING: -dev

jobs:
  release:
    strategy:
      matrix:
        architecture: [x86_64, arm64]
    name: Release (${{ matrix.architecture }})
    runs-on: ${{ matrix.architecture == 'x86_64' && 'ubuntu-latest' || matrix.architecture == 'arm64' && 'ubuntu-latest-arm' }}
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
          echo DATE_RELEASE=$(echo "`date +'%Y.%m.%d'`") >> $GITHUB_OUTPUT

      - name: Login to Local ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.LOCAL_ACR_URL }}
          username: ${{ vars.LOCAL_ACR_USERNAME }}
          password: ${{ secrets.LOCAL_ACR_PASSWORD }}

      - name: Build & Push to Local ACR
        uses: docker/build-push-action@v6
        with:
          platforms: |
            linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_BASE }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.DATE_RELEASE }}${{ env.IMAGE_TAG_ENDING }}
            ${{ env.IMAGE_BASE }}/${{ steps.meta.outputs.REPO_NAME }}:latest${{ env.IMAGE_TAG_ENDING }}

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   container:
  #     image: catthehacker/ubuntu:act-latest
  #   steps:
  #     - name: Run container and capture logs
  #       env:
  #         SWITCH_HOST: 
  #         SWITCH_USERNAME: 
  #         SWITCH_PASSWORD: 
  #         SFTP_HOST: 
  #         SFTP_USERNAME: 
  #         SFTP_PASSWORD: 
  #         SFTP_PATH: 
  #         PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER }}
  #         PUSHOVER_APP_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
  #       run: |
  #         docker run --name test ${{ env.IMAGE_BASE }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.DATE_RELEASE }}${{ env.IMAGE_TAG_ENDING }} /bin/bash -c "/app/setup.sh; /app/run.sh"
  #         docker wait test
  #         docker logs test > logs.txt
  #         docker rm test

  #     - name: Send Logs via Email
  #       uses: dawidd6/action-send-mail@v6
  #       with:
  #         connection_url: ${{ secrets.SMTP_CONNECTION }}
  #         subject: 
  #         to: ${{ vars.SMTP_RECEIVER }}
  #         from: Gitea DevOps - Test Results for ${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.DATE_RELEASE }}${{ env.IMAGE_TAG_ENDING }}
  #         body: Please see attached logs file.
  #         attachments: logs.txt

  report:
    name: Report
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: 
      - release
      # - test
    steps:
      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
          echo DATE_RELEASE=$(echo "`date +'%Y.%m.%d'`") >> $GITHUB_OUTPUT

      - name: Report of Success
        if: needs.release.result == 'success' && needs.deploy.result == 'success'
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        with:
          title: Gitea DevOps
          message: ✅ Built/Pushed & Tested ${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.DATE_RELEASE }}${{ env.IMAGE_TAG_ENDING }} app!

      - name: Report of Failure
        if: needs.release.result != 'success' && needs.deploy.result != 'success'
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        with:
          title: Gitea DevOps
          message: ❌ Unable to build/push & test ${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.DATE_RELEASE }}${{ env.IMAGE_TAG_ENDING }} app.
