name: Build/Push App for Production
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    steps:
      - name: Build Image(s)
        uses: https://${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/gitea-workflows-builder@main
        with:
          registry_url: ${{ vars.LOCAL_ACR_URL }}
          registry_username: ${{ vars.LOCAL_ACR_USERNAME }}
          registry_password: ${{ secrets.LOCAL_ACR_PASSWORD }}
          development: true

  report:
    name: Report
    continue-on-error: true
    needs: 
      - release
    steps:
      - name: Notify User
        uses: https://${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/gitea-workflows-notification@main
        with:
          success: needs.release.result == 'success'
          development: false
          pushover_user: ${{ secrets.PUSHOVER_USER }}
          pushover_token: ${{ secrets.PUSHOVER_TOKEN }}
